bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================

security:
  basic:
    enabled: false

spring:
  zipkin:
    base-url: http://zipkin-server:9411/

management:
  tracing:
    sampling:
      probability: 1
    enabled: true
  endpoints:
    web:
      exposure:
        include: info,matric,env,openapi, swagger-ui
  endpoint:
    env:
      enabled: true
    info:
      enabled: true

