paytm.payment:
  sandbox:
    merchantId: 1234
    merchantKey: 123564
    channelId: WEB
    industryTypeId: Retail
    website: WEBSTAGING
    paytmUrl: https://securegw-stage.paytm.in/order/process 
    callbackUrl: http://localhost:8080/pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantId}
      CHANNEL_ID: ${paytm.payment.sandbox.channelId}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industryTypeId} 
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
  mobile: 8152864826
  email: manjitsharma963@gmail.com


bezkoder:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    
security:
  basic:
    enabled: false

